formatter: "markdown" # this is required

version: ""

header-from: main.tf
footer-from: ""

content: |-
  ## Example

  ```hcl
  {{ include "examples/full/main.tf" }}
  ```
  
  You can use the following rego as a starting point for your cost restriction policy:
  ```rego
  {{ include "examples/full/cost_restriction.rego" }}
  ```

  {{ .Inputs }}

output:
  file: "README.md"
  mode: create

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

#settings:
#  anchor: true
#  color: true
#  default: true
#  description: false
#  escape: true
#  hide-empty: false
#  html: true
#  indent: 2
#  lockfile: true
#  read-comments: true
#  required: true
#  sensitive: true
#  type: true
